# Generated by Django 3.1.7 on 2021-10-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_auto_20211006_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='padd',
            new_name='par_address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='pemail',
            new_name='par_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='pfname',
            new_name='par_first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='plname',
            new_name='par_last_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='pphone',
            new_name='par_phone',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sadd',
            new_name='stud_address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='semail',
            new_name='stud_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sfname',
            new_name='stud_first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='slname',
            new_name='stud_last_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sphone',
            new_name='stud_phone',
        ),
    ]
